---

- name: install the nginx rpm from a remote repo
  yum:
    name: https://dl.grafana.com/oss/release/grafana-6.3.5-1.x86_64.rpm
    state: present
  become: true
  #become_user: babu
  become_method: sudo

- name: Executing a Command Using Shell Module 
  shell:  /sbin/chkconfig --add grafana-server; systemctl enable grafana-server.service; systemctl daemon-reload; systemctl start grafana-server; systemctl status grafana-server
  become: true
  #become_user: babu
  become_method: sudo
