---
- name: Executing a Command Using Shell Module 
  shell: sudo yum install https://dl.grafana.com/oss/release/grafana-6.3.5-1.x86_64.rpm ; sudo /sbin/chkconfig --add grafana-server; sudo systemctl enable grafana-server.service; sudo systemctl daemon-reload; sudo systemctl start grafana-server; sudo systemctl status grafana-server
